massaman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipe/', include('recipe.urls')),
    path('meal/', include('meal.urls')),
    path('', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meal/urls.py
from django.urls import path
from . import views

app_name = 'meal'
urlpatterns = [
    path("", views.meal_monthly, name="meal_monthly"),
    path("<int:year>/<int:month>/", views.meal_monthly, name="meal_monthly"),
    path("<int:year>/<int:month>/list/", views.meal_monthly_list, name="meal_monthly_list"),
    path("<int:year>/<int:month>/<int:day>/", views.meal_daily, name="meal_daily"),
    path("create/", views.meal_create, name="meal_create"),
    path("edit/<int:mealid>/", views.meal_create, name="meal_edit"),

    # Backend
    path("submit/", views.meal_submit, name="meal_submit"),
    path("delete/", views.meal_delete, name="meal_delete"),
    path("get_monthly/", views.get_monthly, name='get_monthly'),
]

recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipe'
urlpatterns = [
    path("", views.browse_all, name="browse_all"),
    path("mine/", views.browse_mine, name="browse_mine"),
    path("create/", views.recipe_create, name="recipe_create"),
    path("edit/<username>/<slug:recipe>/", views.recipe_create, name="recipe_edit"),

    # Backend
    path("create/submit/", views.recipe_submit, name="recipe_submit"),
    path("edit/<username>/<slug:recipe>/submit/", views.recipe_submit, name="recipe_submit_edit"),
    path("delete/", views.recipe_delete, name="recipe_delete"),

    path("<username>/<slug:recipe>/", views.recipe_detail, name="recipe_detail"),
]

recipe/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.db.models import Q
from django.urls import reverse
from django.utils.text import slugify

from taggit.managers import TaggableManager

from .fields import OrderField
from meal.models import Meal
from pantry.models import Ingredient

class PublicManager(models.Manager):
    """Manager to get queryset consisting of public recipes."""
    def get_queryset(self):
        return super(PublicManager, self).get_queryset().filter(status='public')

class AccessibleManager(models.Manager):
    """Manager to get queryset of accessible recipes,
       which includes public recipes and 
       the recipes created by a logged-in user."""
    def for_user(self, user):
        query = Q(status='public')
        publicOnly = self.get_queryset().filter(query)
        if user.is_anonymous:
            return publicOnly
        query = query | Q(owner=user)
        own = self.get_queryset().filter(query)
        return own

class Recipe(models.Model):
    """Model representing a recipe."""
    STATUS_CHOICES = (
        ('public', 'Public'),
        ('private', 'Private'),
    )
    owner = models.ForeignKey(User, related_name='user_recipes', on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    status = models.CharField(max_length=7, choices=STATUS_CHOICES, default='public')
    servings = models.PositiveIntegerField()
    make_time = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    tags = TaggableManager(blank=True)
    picture = models.ImageField(blank=True, upload_to='images/%Y/%m/%d/')
    url = models.URLField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=100, unique=True)
    meals = models.ManyToManyField(Meal, related_name='meal_recipes', blank=True)

    ingredients = GenericRelation(Ingredient)

    objects = models.Manager()
    public = PublicManager()
    accessible = AccessibleManager()

    class Meta:
        ordering = ('-updated',)
    
    def __str__(self):
        return self.title

    # https://kodnito.com/posts/slugify-urls-django/
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Recipe, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('recipe:recipe_detail', args=[self.owner.username, self.slug])

class Instruction(models.Model):
    """Model representing the instruction of a recipe."""
    instruction = models.TextField()
    recipe = models.ForeignKey(Recipe, related_name='instructions', on_delete=models.CASCADE)
    order = OrderField(blank=True, for_fields=['recipe'])

    def __str__(self):
        result = self.instruction
        if len(result) > 30:
            result = result[:30] + "..."
        return str(self.order) + ". " + result

recipe/forms.py
from django import forms
from django.forms.models import inlineformset_factory

from .models import Recipe, Instruction

InstructionFormSet = inlineformset_factory(Recipe, Instruction, 
        fields=['instruction'], extra=1, can_delete=True)

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('title', 'status', 'servings', 'make_time', 'description', 'tags', 'picture', 'url')

recipe/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404, JsonResponse, QueryDict
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from .forms import RecipeForm, InstructionFormSet
from .models import Recipe
from pantry.forms import IngredientFormSet
from pantry.models import Ingredient

def browse(request, recipe_list, personal_page=False):
    """Get page and recipe for a browsing page."""
    paginator = Paginator(recipe_list, 12)
    page = request.GET.get('page')
    try:
        recipes = paginator.page(page)
    except PageNotAnInteger:
        recipes = paginator.page(1)
    except EmptyPage:
        recipes = paginator.page(paginator.num_pages)
    return render(request, 'recipe/browse.html', {'recipes': recipes, 'page': page, 'personal_page': personal_page})

def browse_all(request):
    """Browsing page for all accessible recipes."""
    recipe_list = Recipe.accessible.for_user(request.user).order_by('-updated')
    return browse(request, recipe_list)
    
@login_required
def browse_mine(request):
    """Browsing page for a user's created recipes."""
    recipe_list = request.user.user_recipes.order_by('-updated')
    return browse(request, recipe_list, True)

def recipe_detail(request, username, recipe):
    """Page showing the details of a recipe."""
    recipe = get_object_or_404(Recipe, slug=recipe, owner__username=username)
    if recipe.status == 'private' and recipe.owner != request.user:
        raise Http404("Unable to access recipe")
    return render(request, 'recipe/recipe_detail.html', {'recipe': recipe})

@login_required
def recipe_create(request, username=None, recipe=None):
    """Page to allow recipe editing or creation."""
    if username and recipe:
        recipe = get_object_or_404(Recipe, slug=recipe, owner__username=username)
        if recipe.owner != request.user:
            raise Http404("Unable to access recipe")
        recipe_form = RecipeForm(instance=recipe)
        ingredient_form = IngredientFormSet(queryset=recipe.ingredients.all())
        instruction_form = InstructionFormSet(instance=recipe)
    else:
        recipe_form = RecipeForm()
        ingredient_form = IngredientFormSet(queryset=Ingredient.objects.none())
        instruction_form = InstructionFormSet()
    
    return render(request, 'recipe/recipe_create.html', {'recipe_form': recipe_form, 'ingredient_form': ingredient_form, 'instruction_form': instruction_form})

@login_required
@require_POST
def recipe_submit(request, username=None, recipe=None):
    """Backend process to save a recipe, its ingredients, and its instructions."""
    recipe_data = QueryDict(request.POST.get('recipeData'))
    ingredient_data = QueryDict(request.POST.get('ingredientData'))
    instruction_data = QueryDict(request.POST.get('instructionData'))
    recipe_image = request.FILES.get('recipeImage')

    # Find recipe, if it already exists
    try:
        recipe = get_object_or_404(Recipe, slug=recipe, owner__username=username)
        if recipe.owner != request.user:
            raise Http404("Unable to access recipe")
        recipe_form = RecipeForm(instance=recipe, data=recipe_data)
    except:
        recipe_form = RecipeForm(recipe_data)

    # Save valid recipe
    if recipe_form.is_valid():
        recipe = recipe_form.save(commit=False)
        recipe.owner = request.user
        recipe.picture = recipe_image
        recipe.save()

        # Save valid instructions
        instruction_form = InstructionFormSet(instance=recipe, data=instruction_data)
        if instruction_form.is_valid():
            instruction_form.save()

        # Save valid ingredients
        ingredient_form = IngredientFormSet(ingredient_data)
        if ingredient_form.is_valid():
            ingredients = ingredient_form.save(commit=False)
            for ingredient in ingredients:
                ingredient.owner = recipe
                ingredient.save()
            
            redirecturl = '/recipe/' + request.user.username + '/' + recipe.slug
            return JsonResponse({'redirecturl': redirecturl})

    return JsonResponse({}, status=500)
    
@login_required
@require_POST
def recipe_delete(request):
    """Backend process to delete a recipe."""
    recipe = get_object_or_404(Recipe, slug=request.POST['slug'], owner__username=request.user)
    recipe.delete()

    return JsonResponse({})

recipe/templates/recipe/browse.html
{% extends "recipe/recipe_base.html" %}
{% load static %}

{% block content %}
  <div id="browse">
    <h1>{% if personal_page %}My{% else %}Browse{% endif %} Recipes</h1>
    {% for recipe in recipes %}
      <div class="recipeblock">
        <a href="{{ recipe.get_absolute_url }}">
          <img src="{% if recipe.picture %}{{ recipe.picture.url }}{% else %}{% static 'img/no_image_light.png' %}{% endif %}">
          <p>{{ recipe.title }}</p>
        </a>
      </div>
    {% empty %}
      <p>No recipes available.</p>
    {% endfor %}
  </div>

  {% include "pagination.html" with page=recipes %}

  <link href="{% static 'css/recipe/recipe.css' %}" rel="stylesheet">
{% endblock %}

recipe/templates/recipe/recipe_base.html
{% extends "base.html" %}
{% load static %}

{% block title %}Recipes{% endblock %}

{% block sidebar %}
  <ul class="links">
    {% if user.is_authenticated %}
      <li>
        <a href="{% url 'recipe:recipe_create' %}">Create new recipe</a>
      </li>
    {% endif %}
    <li>
      <a href="{% url 'recipe:browse_all' %}">Browse recipes</a>
    </li>
  </ul>
{% endblock %}

recipe/templates/recipe/recipe_create.html
{% extends "recipe/recipe_base.html" %}
{% load static %}

{% block title %}New Recipe{% endblock %}

{% block content %}
  <div class="recipe">
    <h1>New Recipe</h1> 
    <div id="main">
      <form>
        {% for field in recipe_form %}
          {% if field.field.required %}* {% endif %}
          {{ field.label_tag }}
          <br>
          {{ field }} 
          {% if field.label == 'Tags' %}<br><i>Separate tags with commas</i>{% endif %}
          <br><br>
        {% endfor %}
        {% csrf_token %}
      </form>
      <p>* Required</p>
    </div>
    <div class="create">
      <div id="instructions">
        <p>Instructions:</p>
        <form>
          {{ instruction_form.management_form }}
          {% csrf_token %}
          {% for form in instruction_form %}
            <div>
              {% for field in form %}
                {% if field.label == 'Instruction' %}
                  {{ field }}
                  <br>
                {% endif %}
                {% if field.label == 'Delete' or field.label == 'Id' %}
                  {{ field.label_tag }} {{ field }}
                  <br>
                {% endif %}
              {% endfor %}
              <br>
            </div>
          {% endfor %}
        </form>
        <button>New instruction</button>
      </div>
      <div id="instructions_empty">
        <div>
          {% with form=instruction_form.empty_form %}
            {% for field in form %}
              {% if field.label == 'Instruction' %}
                {{ field }}
                <br>
              {% endif %}
              {% if field.label == 'Delete' or field.label == 'Id' %}
                {{ field.label_tag }} {{ field }}
                <br>
              {% endif %}
            {% endfor %}
            <br>
          {% endwith %}
          </div>
      </div>
      <div id="ingredients">
        <p>Ingredients:</p>
          <form>
            {{ ingredient_form.management_form }}
            {% csrf_token %}
            {% for form in ingredient_form %}
              <div>
                {% for field in form %}
                  {{ field.label_tag }} 
                  <br>
                  {{ field }}
                  <br>
                {% endfor %}
                <br>
              </div>
            {% endfor %}
          </form>
        <button>New ingredient</button>
      </div>
      <div id="ingredients_empty">
        <div>
          {% with form=ingredient_form.empty_form %}
            {% for field in form %}
              {{ field.label_tag }}
              <br>
              {{ field }}
              <br>
            {% endfor %}
            <br>
          {% endwith %}
        </div>
      </div>
    </div>
    <p class="error"></p>
    <div class="submit">
      <form>
        {% csrf_token %}
        <input type="submit" value="Save Recipe">
      </form>
    </div>
  </div>

  <link href="{% static 'css/recipe/recipe.css' %}" rel="stylesheet">
  <script src="{% static 'scripts/recipe/create.js' %}"></script>
{% endblock %}

recipe/templates/recipe/recipe_detail.html
{% extends "recipe/recipe_base.html" %}
{% load static %}

{% block title %}{{ recipe.title }}{% endblock %}

{% block content %}
  <div class="recipe">
    <h1 class="title">{{ recipe.title }}</h1>
    <div class="image">
      <img src="{% if recipe.picture %}{{ recipe.picture.url }}{% else %}{% static 'img/no_image_dark.png' %}{% endif %}">
    </div>
    <div class="details">
      <p>Creator: {% if recipe.owner %}{{ recipe.owner.username }}{% else %}[deleted user]{% endif %}</p>
      <p>Make time: {{ recipe.make_time }}</p>
      <p>Number of servings: {{ recipe.servings }}</p>
      <span>
        {% for tag in recipe.tags.all %}
          <a href="#">{{ tag.name }}</a>
          {% if not forloop.last %}|{% endif %}
        {% endfor %}
      </span>
      {% if recipe.url %}
        <p><a href="{{ recipe.url }}" target="_blank">[Link]</a></p>
      {% endif %}
      {% if recipe.owner.username == user.username %}
        <span>
          <button class="edit">Edit Recipe</button>
          <button class="delete">Delete Recipe</button>
        </span>
        <div class="delete">
          <p>Are you sure you want to delete this recipe?</p>
          <button class="yes">Yes</button>
          <button class="no">Nevermind</button>
        </div>
      {% endif %}
    </div>
    <p class="description">{{ recipe.description }}</p>
    <div class="numbered">
      <h2>Ingredients</h2>
      <ol>
        {% for ingredient in recipe.ingredients.all %}
          <li>{{ ingredient }}</li>
        {% endfor %}
      </ol>
    </div>
    <div class="numbered">
      <h2>Instructions</h2>
      <ol>
        {% for instruction in recipe.instructions.all %}
          <li>{{ instruction.instruction }}</li>
        {% endfor %}
      </ol>
    </div>
    <p>Posted on {{ recipe.created }}, last updated {{ recipe.updated }}.</p>
  </div>

  <link href="{% static 'css/recipe/recipe.css' %}" rel="stylesheet">
  <script src="{% static 'scripts/recipe/detail.js' %}"></script>
{% endblock %}