account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'
urlpatterns = [
    path("", views.landing, name="landing"),
    path("authenticate/", views.authenticate_view, name="authenticate"),
    path("settings/", views.settings_view, name="settings"),
    path("logout/", views.logout_view, name="logout"),
    
    # Background processes
    path("login/", views.login_submit, name="login"),
    path("register/", views.register_submit, name="register"),
    path("change_settings/", views.settings_submit, name="change_settings"),
    path("change_password/", views.password_change_submit, name="change_password"),
    path("delete_account/", views.delete_account, name="delete_account"),
]

massaman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipe/', include('recipe.urls')),
    path('meal/', include('meal.urls')),
    path('', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meal/urls.py
from django.urls import path
from . import views

app_name = 'meal'
urlpatterns = [
    path("", views.meal_monthly, name="meal_monthly"),
    path("<int:year>/<int:month>/", views.meal_monthly, name="meal_monthly"),
    path("<int:year>/<int:month>/list/", views.meal_monthly_list, name="meal_monthly_list"),
    path("<int:year>/<int:month>/<int:day>/", views.meal_daily, name="meal_daily"),
    path("create/", views.meal_create, name="meal_create"),
    path("edit/<int:mealid>/", views.meal_create, name="meal_edit"),

    # Backend
    path("submit/", views.meal_submit, name="meal_submit"),
    path("delete/", views.meal_delete, name="meal_delete"),
    path("get_monthly/", views.get_monthly, name='get_monthly'),
]

recipe/urls.py
from django.urls import path
from . import views

app_name = 'recipe'
urlpatterns = [
    path("", views.browse_all, name="browse_all"),
    path("mine/", views.browse_mine, name="browse_mine"),
    path("create/", views.recipe_create, name="recipe_create"),
    path("edit/<username>/<slug:recipe>/", views.recipe_create, name="recipe_edit"),

    # Backend
    path("create/submit/", views.recipe_submit, name="recipe_submit"),
    path("edit/<username>/<slug:recipe>/submit/", views.recipe_submit, name="recipe_submit_edit"),
    path("delete/", views.recipe_delete, name="recipe_delete"),

    path("<username>/<slug:recipe>/", views.recipe_detail, name="recipe_detail"),
]

account/models.py
from django.db import models

# Create your models here.

account/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')
    
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError("Passwords do not match.")
        return cd['password2']

class SettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name')

class DeleteAccountForm(forms.Form):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    def __init__(self, user, data=None):
        self.user = user
        super(DeleteAccountForm, self).__init__(data=data)

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError("Passwords do not match")
        elif not self.user.check_password(cd['password2']):
            raise forms.ValidationError("Wrong password entered")

account/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from .forms import DeleteAccountForm, LoginForm, RegisterForm, SettingsForm

def landing(request):
    """Default landing page for Massaman."""
    if request.user.is_authenticated:
        return redirect('recipe:browse_all')
    return render(request, 'account/landing.html')

def authenticate_view(request):
    """Set up necessary forms for authentication page."""
    # Authenticated users shouldn't log in again.
    if request.user.is_authenticated:
        return redirect('recipe:browse_all')
    
    login_form = LoginForm()
    register_form = RegisterForm()
    context = {
        'login_form': login_form,
        'register_form': register_form
    }
    return render(request, 'account/authenticate.html', context)

@login_required
def settings_view(request):
    """Set up necessary forms for settings page."""
    settings_form = SettingsForm(instance=request.user)
    password_change_form = PasswordChangeForm(request.user)
    delete_account_form = DeleteAccountForm(request.user)

    context = {'settings_form': settings_form, 
               'password_change_form': password_change_form,
               'delete_account_form': delete_account_form}
    return render(request, 'account/settings.html', context)

@require_POST
def login_submit(request):
    """Background process: Try to log a user in."""
    form = LoginForm(data=request.POST)
    if form.is_valid():
        data = form.cleaned_data
        user = authenticate(request, username=data['username'], password=data['password'])
        if user is None:
            # Account does not exist.
            return JsonResponse({}, status=500)
        login(request, user)
        return JsonResponse({})
    
    # Improper login form.
    return JsonResponse({}, status=500)

@require_POST
def register_submit(request):
    """Background process: Try to register a new user."""
    form = RegisterForm(data=request.POST)
    if form.is_valid():
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password1'])
        user.save()
        login(request, user)
        return JsonResponse({})

    # Improper register form.
    error_dict = get_error_dict(form)
    return JsonResponse(error_dict, status=500)

@login_required
@require_POST
def settings_submit(request):
    """Background process: Try to update an existing user's
       username, first name, and last name."""
    user_form = SettingsForm(instance=request.user, data=request.POST)
    if user_form.is_valid():
        user_form.save()
        return JsonResponse({})

    return JsonResponse({}, status=500)

@login_required
@require_POST
def password_change_submit(request):
    """Background process: Try to change a user's password."""
    password_form = PasswordChangeForm(request.user, data=request.POST)
    if password_form.is_valid():
        user = password_form.save()
        update_session_auth_hash(request, user)
        return JsonResponse({})
    else:
        error_dict = get_error_dict(password_form)
        return JsonResponse(error_dict, status=500)

@login_required
@require_POST
def delete_account(request):
    """Background process: Try to delete a user's account."""
    delete_account_form = DeleteAccountForm(user=request.user, data=request.POST)
    if delete_account_form.is_valid():
        to_delete = request.user
        logout(request)
        to_delete.delete()
        return JsonResponse({})
    return JsonResponse({}, status=500)

def logout_view(request):
    """Log a user out."""
    logout(request)
    return redirect('account:landing')

def get_error_dict(form):
    """Creates a flattened list of errors, 
       then sets the list as the value corresponding 
       to key 'errors'."""
    errors = list(dict(form.errors).values())
    errors_flattened = [er for error in errors for er in error]
    return {'errors': errors_flattened}

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'img/logo.ico' %}" rel="icon">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <script src="{% static 'scripts/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'scripts/js.cookie.js' %}"></script>
    <script src="{% static 'scripts/base.js' %}"></script>
  </head>
  <body>
    <div id="header">
      <ul>
        <li><img src="{% static 'img/logo_trans.png' %}"></li>
        <li>
          <h1>
            <a href="{% url 'account:landing' %}">Massaman</a>
          </h1>
        </li>
        <div class="buttons">
          {% if request.user.is_authenticated %}
            <li>
              <a class="settings" href=""><img src="{% static 'img/settings_light.png' %}"></a>
            </li>
            <li>
              <a class="general" href="#"><img src="{% static 'img/menu_light.png' %}"></a>
            </li>
          {% else %}
            <li>
              <a href="{% url 'account:authenticate' %}">Login/Register</a>
            </li>
          {% endif %}
          <li>
            <a href="#"><img src="{% static 'img/search_light.png' %}"></a>
          </li>
        </div>
      </ul>
    </div>
    <div class="menu settings">
      <ul class="links">
        <li>
          <a href="{% url 'account:settings' %}">Settings</a>
        </li>
        <li>
          <a href="#">Help</a>
        </li>
        <li>
          <a href="{% url 'account:logout' %}">Logout</a>
        </li>
      </ul>
    </div>
    <div class="menu general">
      <ul class="links">
        <li>
          <a href="{% url 'recipe:browse_mine' %}">My Recipes</a>
        </li>
        <li>
          <a href="{% url 'meal:meal_monthly' %}">My Meals</a>
        </li>
        <li>
          <a href="#">My Pantry</a>
        </li>
        <li>
          <a href="#">My Shopping List</a>
        </li>
      </ul>
    </div>
    <div id="sidebar">
      {% block sidebar %}{% endblock %}
    </div>
    <div id="content">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>