massaman/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipe/', include('recipe.urls')),
    path('meal/', include('meal.urls')),
    path('', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meal/urls.py
from django.urls import path
from . import views

app_name = 'meal'
urlpatterns = [
    path("", views.meal_monthly, name="meal_monthly"),
    path("<int:year>/<int:month>/", views.meal_monthly, name="meal_monthly"),
    path("<int:year>/<int:month>/list/", views.meal_monthly_list, name="meal_monthly_list"),
    path("<int:year>/<int:month>/<int:day>/", views.meal_daily, name="meal_daily"),
    path("create/", views.meal_create, name="meal_create"),
    path("edit/<int:mealid>/", views.meal_create, name="meal_edit"),

    # Backend
    path("submit/", views.meal_submit, name="meal_submit"),
    path("delete/", views.meal_delete, name="meal_delete"),
    path("get_monthly/", views.get_monthly, name='get_monthly'),
]

meal/models.py
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models

from pantry.models import Ingredient

class Meal(models.Model):
    """Model representing a meal."""
    RATING_CHOICES = (
        (0, 'none'),
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    owner = models.ForeignKey(User, related_name='user_meals', on_delete=models.CASCADE)
    when = models.DateTimeField()
    recipes = models.ManyToManyField('recipe.Recipe', related_name='recipe_meals', blank=True)
    rating = models.PositiveIntegerField(choices=RATING_CHOICES, default=0)
    comments = models.TextField(blank=True)

    foods = GenericRelation(Ingredient)

    class Meta:
        ordering = ('when',)
    

meal/forms.py
from django import forms

from .models import Meal
from pantry.models import Ingredient
from recipe.models import Recipe

class MealForm(forms.ModelForm):
    class Meta:
        model = Meal
        fields = ('when', 'comments', 'recipes')
    
    def __init__(self, user=None, *args, **kwargs):
        super(MealForm, self).__init__(*args, **kwargs)

        if user:
            # Only show recipes accessible to a user
            self.fields['recipes'] = forms.ModelMultipleChoiceField(queryset=Recipe.accessible.for_user(user), required=False)
        

meal/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import Http404, JsonResponse, QueryDict
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.views.decorators.http import require_POST

import datetime
import json 

from .forms import MealForm
from .models import Meal
from pantry.forms import IngredientFormSet
from pantry.models import Ingredient

@login_required
def meal_create(request, mealid=None):
    """Page to allow recipe editing or creation.
    """
    if mealid:
        meal = get_object_or_404(Meal, id=mealid)
        if meal.owner != request.user:
            raise Http404("Unable to access meal")
        meal_form = MealForm(request.user, instance=meal)
        food_form = IngredientFormSet(queryset=meal.foods.all())
    else: 
        meal_form = MealForm(request.user)
        food_form = IngredientFormSet(queryset=Ingredient.objects.none())

    return render(request, 'meal/create.html', {'meal_form': meal_form, 'food_form': food_form, 'mealid': mealid})

@login_required
@require_POST
def meal_submit(request):
    """Backend process to save a meal and
       its related foods."""
    meal_data = QueryDict(request.POST['mealData'])
    food_data = QueryDict(request.POST['foodData'])

    try:
        # Editing a meal
        mealid = request.POST['mealid']
        meal = get_object_or_404(Meal, id=mealid)
        if meal.owner != request.user:
            raise Http404("Unable to access meal")
        meal_form = MealForm(request.user, instance=meal, data=meal_data)
    except:
        # Creating a meal
        meal_form = MealForm(request.user, data=meal_data)

    # Save meal
    if meal_form.is_valid():
        meal = meal_form.save(commit=False)
        meal.owner = request.user
        meal.save()
        meal_form.save_m2m()

        # Save valid ingredients
        food_form = IngredientFormSet(food_data)
        if food_form.is_valid():
            food = food_form.save(commit=False)
            for val in food:
                val.owner = meal
                val.save()

            redirecturl = '/meal/' + str(meal.when.year) + '/' + str(meal.when.month) + '/' + str(meal.when.day)
            
            return JsonResponse({'redirecturl': redirecturl})
    
    return JsonResponse({}, status=500)

@login_required
@require_POST
def meal_delete(request):
    """Backend process to delete a meal."""
    mealid = request.POST['mealid']
    meal = get_object_or_404(Meal, id=mealid)
    if meal.owner != request.user:
        raise Http404("Unable to access meal")
    
    meal.delete()

    return JsonResponse({})

@login_required
def meal_monthly(request, year=None, month=None):
    """Page to show a calendar view
       with summary of meals.
       Note that actual meal information is obtained
       via a POST request on page load so that JS
       can be used to create a dynamic calendar.
    """
    return render(request, 'meal/month.html')

@login_required
@require_POST
def get_monthly(request):
    """Backend process to get the meals
       for a particular month of the year.
    """
    month = request.POST['month']
    year = request.POST['year']
    query = Q(owner=request.user) & Q(when__month=month) & Q(when__year=year)
    meals = Meal.objects.filter(query)

    meals_js = list()
    for meal in meals:
        obj = dict()
        obj['day'] = meal.when.day
        obj['hour'] = meal.when.hour
        obj['minute'] = meal.when.minute
        meals_js.append(obj)
    
    return JsonResponse({'meals': meals_js})

@login_required
def meal_daily(request, year, month, day):
    query = Q(owner=request.user) & Q(when__day=day) & Q(when__month=month) & Q(when__year=year)
    meals = Meal.objects.filter(query)

    return render(request, 'meal/day.html', {'meals': meals})

@login_required
def meal_monthly_list(request, year, month):
    query = Q(owner=request.user) & Q(when__month=month) & Q(when__year=year)
    meals = Meal.objects.filter(query)

    return render(request, 'meal/month_list.html', {'meals': meals, 'month': month, 'year': year})

meal/templates/meal/create.html
{% extends "meal/meal_base.html" %}
{% load static %}

{% block content %}
  <div class="meal">
    <h1>New Meal</h1>
    <div id="main">
      <form>
        {% csrf_token %}
        {% for field in meal_form %}
          {% if field.label == 'When' %}* {% endif %}
          {{ field.label_tag }}
          <br>
          {{ field }}
          <br>
          <br>
        {% endfor %}
      </form>
      <button>Clear Recipes</button>
      <p>* Required</p>
    </div>
    <br>
    <div id="foods">
      <p>Other Foods:</p>
      <form>
        {{ food_form.management_form }}
        {% csrf_token %}
        {% for form in food_form %}
          <div>
            {% for field in form %}
              {{ field.label_tag }}
              <br>
              {{ field }}
              <br>
            {% endfor %}
            <br>
          </div>
        {% endfor %}
      </form>
      <button>New food</button>
    </div>
    <div id="foods_empty">
      <div>
        {% with form=food_form.empty_form %}
          {% for field in form %}
            {{ field.label_tag }}
            <br>
            {{ field }}
            <br>
          {% endfor %}
          <br>
        {% endwith %}
      </div>
    </div>
    <br>
    <p class="error"></p>
    <div class="submit">
      <form>
        {% csrf_token %}
        <input type="submit" value="Save Meal">
      </form>
    </div>
  </div>

  <script src="{% static 'scripts/jquery.datetimepicker.full.min.js' %}"></script>
  <link href="{% static 'css/jquery.datetimepicker.min.css' %}" rel="stylesheet">
  <script src="{% static 'scripts/meal/create.js' %}"></script>
{% endblock %}

meal/templates/meal/day.html
{% extends "meal/meal_base.html" %}
{% load static %}

{% block content %}
  <h1>Daily Meals</h1>
  {% include "meal/list.html" with meals=meals %}
{% endblock %}

meal/templates/meal/list.html
{% load static %}

<div class="meal_list">
  {% for meal in meals %}
    <div class="meal_block" data-mid="{{ meal.id }}">
      <h2>{{ meal.when.date }} | {{ meal.when.time }}</h2>
      <h3>Recipes:</h3>
      <ul>
        {% for recipe in meal.recipes.all %}
          <li><a href="{{ recipe.get_absolute_url }}">{{ recipe }}</a></li>
        {% empty %}
          <li>No recipes</li>
        {% endfor %}
      </ul>
      <h3>Other foods:</h3>
      <ul>
        {% for food in meal.foods.all %}
          <li>{{ food }}</li>
        {% empty %}
          <li>No other foods</li>
        {% endfor %}
      </ul>
      {% if meal.comments %}
        <h3>Comments:</h3>
        {{ meal.comments }}
        <br>
      {% endif %}
      <br>
      <span>
        <button class="edit">Edit Meal</button>
        <button class="delete">Delete Meal</button>
      </span>
    </div>
  {% empty %}
    <p>No meals available.</p>
    <p>Why not <a href="{% url 'meal:meal_create' %}">create a new meal</a>?</p>
  {% endfor %}

  <div class="delete">
    <p>Are you sure you want to delete this recipe?</p>
    <button class="yes">Yes</button>
    <button class="no">Nevermind</button>
  </div>

  <link href="{% static 'css/meal/list.css' %}" rel="stylesheet">
  <script src="{% static 'scripts/meal/list.js' %}"></script>
</div>

meal/templates/meal/meal_base.html
{% extends "base.html" %}
{% load static %}

{% block title %}Meals{% endblock %}

{% block sidebar %}
  <ul class="links">
    <li>
      <a href="{% url 'meal:meal_create' %}">Create new meal</a>
    </li>
    <li>
      <a href="{% url 'meal:meal_monthly' %}">This month's meals</a>
    </li>
  </ul>
{% endblock %}

meal/templates/meal/month.html
{% extends "meal/meal_base.html" %}
{% load static %}

{% block content %}
  <div id="calendar">
    <div class="months">
      <span><a id="prev_month">←</a></span>
      <span><a id="this_month"></a></span>
      <span><a id="next_month">→</a></span>
    </div>
    <ul class="weekdays">
      <li>Su</li>
      <li>M</li>
      <li>T</li>
      <li>W</li>
      <li>Th</li>
      <li>F</li>
      <li>Sa</li>
    </ul>
    <ul class="main">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li></li>
      <li>1</li>
      <li>2</li>
      <li>3</li>
      <li>4</li>
      <li>5</li>
      <li>6</li>
      <li>7</li>
      <li>8</li>
      <li>9</li>
      <li>10</li>
      <li>11</li>
      <li>12</li>
      <li>13</li>
      <li>14</li>
      <li>15</li>
      <li>16</li>
      <li>17</li>
      <li>18</li>
      <li>19</li>
      <li>20</li>
      <li>21</li>
      <li>22</li>
      <li>23</li>
      <li>24</li>
      <li>25</li>
      <li>26</li>
      <li>27</li>
      <li>28</li>
      <li>29</li>
      <li>30</li>
      <li>31</li>
    </ul>
  </div>

  <link href="{% static 'css/meal/month.css' %}" rel="stylesheet">
  <script src="{% static 'scripts/jquery-ui.min.js' %}"></script>
  <link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">
  <script src="{% static 'scripts/meal/month.js' %}"></script>
{% endblock %}

meal/templates/meal/month_list.html
{% extends "meal/meal_base.html" %}
{% load static %}

{% block content %}
  <h1>{{ month }} {{ year }}</h1>
  {% include "meal/list.html" with meals=meals %}

  <script>
    // Change header to reflect actual month name
    $(function() {
      let date = $('#content h1').text().split(" ");
      let month = monthName(parseInt(date[0]));
      $('#content h1').text("Monthly Meals | " + month + " " + date[1]);
    });
  </script>
{% endblock %}